#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\room.bof

BOFS =  barlqrm.bof crnthrm.bof jasperrm.bof kocarm.bof marnrm.bof tosrm.bof \
   ghall.bof godroom.bof razarm.bof badland2.bof castle1c.bof cave3.bof \
   dungeon.bof field1.bof bazmans.bof hermhut.bof monsroom.bof outgrace.bof \
   profroom.bof temple.bof tempkra.bof tempqor.bof temprii.bof castle2a.bof \
   castle2d.bof mockers.bof duke1.bof duke2.bof duke3.bof \
   univ.bof castle2e.bof gallery.bof bowhut.bof tpost1.bof tpost2.bof \
   rentroom.bof necarena.bof desert.bof qormasland.bof


# Removed
#        a4.bof a5.bof b4.bof b5.bof b7.bof b8.bof c3.bof c8.bof c9.bof \
#        d8.bof d9.bof e8.bof e9.bof f5.bof f6.bof f7.bof f9.bof

!include $(KODDIR)\kod.mak
