#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\razatwn.bof
BOFS  = razaapoth.bof razaelder.bof razabsmith.bof razabart.bof razainnk.bof

!include $(KODDIR)\kod.mak
