#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\crnthtwn.bof
BOFS  = cnurchin.bof cngrocer.bof cnsarge.bof cninnk.bof cntailor.bof cnmuseumguard.bof

!include $(KODDIR)\kod.mak
