#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\passive.bof
BOFS = tree.bof spell.bof boulder.bof news.bof trestype.bof arsign01.bof \
   throne.bof pillar.bof chandelr.bof skull.bof body.bof \
   fountain.bof tombston.bof stool.bof table.bof shrub.bof sngltree.bof \
   bank.bof sign-ar.bof sign-ar2.bof barstool.bof sign.bof \
   skill.bof treeoak.bof treepine.bof newslink.bof decoitem.bof \
   mananode.bof lever.bof trance.bof switch.bof guild.bof guildcmd.bof \
   gldlever.bof brain.bof quillpen.bof sun.bof moon.bof asssign.bof\
   tallbush.bof dispensr.bof fountjet.bof gstlever.bof \
   farytree.bof itematt.bof quest.bof questnode.bof storage.bof \
   ornobj.bof yrxltree.bof statue.bof mvsector.bof dice.bof shrine.bof \
   bookped.bof flikerer.bof viewglbe.bof trgtglbe.bof \
   nectome.bof modlnode.bof wrmtrail.bof shrinfog.bof \
   bell.bof dflycage.bof pillow.bof ghostitm.bof ventstem.bof \
   evntsign.bof maillist.bof objectatt.bof roomflagicon.bof \
   questtemplate.bof honrsign.bof

!include $(KODDIR)\kod.mak
