#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\oldtown.bof

BOFS = oldjas.bof oldmar.bof oldbarln.bof oldbarls.bof oldcornoth.bof \
       oldcoruniv.bof oldtos.bof oldeasttos.bof oldtosinn.bof oldtosapoth.bof \
       oldtossmith.bof

!include $(KODDIR)\kod.mak

