#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\debuff.bof
BOFS = blind.bof cursewp.bof dazzle.bof disease.bof dishonor.bof forget.bof \
       hold.bof seduce.bof vertigo.bof drain.bof slow.bof

!include $(KODDIR)\kod.mak
