#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\monster.bof
BOFS  = ant.bof centip.bof cow.bof ent.bof fairy.bof fungbst.bof ghost.bof \
        giarat.bof mummy.bof orc.bof redant.bof scorpion.bof skel.bof \
        elemental.bof slime.bof spdrbaby.bof spdrquen.bof spider.bof \
        troll.bof yeti.bof zombie.bof thief.bof revenant.bof frogman.bof iceper.bof \
        priestes.bof evfairy.bof lupogg.bof tester.bof avar.bof avchief.bof \
        avshaman.bof reflectn.bof guard.bof orccave.bof orcboss.bof shadowb.bof \
        orcwiza.bof dfly.bof dflyq.bof lupking.bof kriipa.bof bossbody.bof \
        stntroll.bof snowrat.bof lich.bof deadlich.bof duskrat.bof thrasher.bof \
        nrthlwrm.bof bramble.bof eviltwin.bof dethspid.bof grdworm.bof human.bof \
        xeochctl.bof dflypet.bof dangel.bof mollusk.bof specmum.bof \
        evilent.bof elephant.bof bunny.bof wolf.bof chupacabra.bof minotaur.bof \
        oldorc.bof oldrat.bof oldcentip.bof npc.bof


!include $(KODDIR)\kod.mak
