#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\towns.bof
BOFS  = barlqtwn.bof crnthtwn.bof jasprtwn.bof marntwn.bof tostwn.bof \
        razatwn.bof kocatwn.bof decoratr.bof ladyphen.bof watcher.bof

!include $(KODDIR)\kod.mak
