#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\razarm.bof

BOFS = raza.bof razainn.bof razasmith.bof razashop.bof razahut.bof \
       razabar.bof razamuseum.bof razahall.bof

!include $(KODDIR)\kod.mak

