#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\crnthrm.bof

BOFS =  cornoth.bof corgroc.bof corhall.bof corinn.bof corwepm.bof cortail.bof \
        corgenhall.bof coruniv.bof cormuseum.bof forgot2.bof

!include $(KODDIR)\kod.mak

